### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Set the multiple PHPUnit versions to support the different PHP versions.
- Using the class-based PHPUnit namespace to support the latest PHPUnit version.
- Using the `expectedException` annotation to be compatible with the different PHPUit versions.
- The one of `hhvm` version test in Travis build will be failed and it's related to this [issue](https://github.com/facebook/hhvm/issues/6954).
I think we should remove the `hhvm` test and let this package require `php-7.1` version at least.

### CODE REVIEW

**Comment by peter279k** [comment]
Hi @zbateson, thank you for your reply.
- Using the different PHPUnit versions for multiple PHP versions because the different PHPUnit versions is for different PHP versions. You can see more details about this in official [PHPUnit doc](https://phpunit.de/).
- In your comment, it seems that you have to use the `php-5.4` to install this package so you have to keep this project requiring `php-5.4`.

I recommend that we can revert the required PHP version `5.4` at least and using the PHPUnit versions are `4.8` and `5.7`.

What do you think? Thanks.

**Comment by zbateson** [comment]
I'm okay with either approach to be honest.  It seems like the hhvm issue will probably be addressed looking at the issue you linked.  Feel free to modify the pull request to either:

- skip tests on hhvm, or
- use phpunit 4.8 and 5.7

Thanks for the explanation about phpunit, I hadn't realized that :)

**Comment by peter279k** [comment]
Hi @zbateson, thank you for your quick reply.
I decide to remove `hhvm` test in Travis CI build and keep the PHP version require `php-5.4` at least :+1: .

Thanks.

**Comment by zbateson** [comment]
Perfect, thanks again!  I'll move it to an allowed failure for now after I merge so we can keep an eye on it as well.

**Pull request merged**
